#!/bin/bash
DEFAULT_OPTIONS="mcpu=native,nodebug,no-write-symbols"

cd ~/.local/share/Steam/steamapps/common/Liftoff/Liftoff_Data/Managed/
for file in ./*.dll
do
    mono --aot=llvm,full,$DEFAULT_OPTIONS -O=all "$file" || \
    mono --aot=full,$DEFAULT_OPTIONS -O=all "$file" || \
    mono --aot=llvm,$DEFAULT_OPTIONS -O=all "$file" || \
    mono --aot=$DEFAULT_OPTIONS -O=all "$file" || \
    mono --aot=llvm,$DEFAULT_OPTIONS "$file" \
    mono --aot=$DEFAULT_OPTIONS "$file"
done
