#!/bin/sh
xrandr --output DisplayPort-0 --mode 2560x1440 --pos 0x0 --rotate normal --rate 144.00 --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --primary --mode 4096x2160 --pos 2560x0 --rotate normal --rate 29.97
