#!/bin/sh
xrandr --output DisplayPort-0 --mode 1280x720 --pos 4096x0 --rotate normal --rate 144.00 --output DisplayPort-1 --mode 1280x720 --pos 4096x0 --rotate normal --rate 60.00 --output DisplayPort-2 --off --output HDMI-A-0 --primary --mode 4096x2160 --pos 0x0 --rotate normal --rate 30.00
